### PR TITLE
Clear selected items when table data changes

### PR DESCRIPTION
**Pull request by nirmaldandalaio**
The selectedItems array should be cleared every time table data changes. An example use case is:

Problem: When user selects a row, it gets added to the selectedItems array. When the row is deleted, the row item still persists in the selectedItems state as an unselect has never been performed and the row doesn't exist now. 

- [x] Solution: Every time table data changes, the selectedItems array should be set to empty if there are any selected Items. This will subsequently call the SelectedItemsChanged (as it an observer on the selectedItems array) event which triggers the change to the state.

- [x] Added test cases to verify the selectedItems array is cleared on table data change.

### CODE REVIEW

**Comment by evanjd** [comment]
I'm concerned this might create regressions on App Engine. We do depend on selectedItems persisting through table data changes (eg. when paging). I'll check this over the next couple of days.

> Problem: When user selects a row, it gets added to the selectedItems array. When the row is deleted, the row item still persists in the selectedItems state as an unselect has never been performed and the row doesn't exist now.

Wouldn't a safer fix be to removed the deleted item from the `selectedItems` array, instead of wiping all selections?

**Comment by nirmaldandalaio** [comment]
@evanjd I understand the concern. In order to do the specific deletion, a unique id is required for each row item which does not exist in this case. Lets talk more about this.

**Comment by evanjd** [comment]
Thanks for this - after our chat I agree your change is the right thing to do for now and have verified there's no regressions in AE. I think there are use cases where having selected items persist through data changes would be useful/expected, but since the grid doesn't handle that properly right now your approach is better than leaving stale copies of deleted records in the `selectedItems` array. 👍

**Comment by sks** [comment]
@evanjd : lets use the `squash and merge ` option in github so that we dont end up with a lot of noise in the commit history.

**Pull request merged**
